export const productTypes = [
    "Cleanser",
    "Cleansing Balm",
    "Cleansing Oil",
    "Cream Cleanser",
    "Face Wash",
    "Foaming Cleanser",
    "Gel Cleanser",
    "Oil Cleanser",
    "Chemical Exfoliator",
    "Peel",
    "Physical Exfoliator / Scrub",
    "Charcoal Mask",
    "Clay Mask",
    "Detox Mask",
    "Mask",
    "Mud Mask",
    "Sheet Mask",
    "Sleeping Mask",
    "Under eye Mask",
    "Face Mist",
    "Day Cream",
    "Eye Cream",
    "Face Cream",
    "Gel cream",
    "Hand Cream",
    "Intensive Moisturizer",
    "Lip Balm",
    "Lip Mask",
    "Lip Oil",
    "Lip Scrub",
    "Face Moisturizer",
    "Night Cream",
    "Tinted Moisturizer",
    "Face Oil",
    "Squalane",
    "AHA (Alpha Hydroxy Acid) Serum",
    "Antioxidant Serum",
    "Azelaic Acid",
    "BHA (Beta Hydroxy Acid) Serum",
    "Brightening Serum",
    "Collagen Serum",
    "Cooling Gel",
    "Glycolic Acid",
    "Hyaluronic Acid Serum",
    "Niacinamide Serum",
    "Peptide Serum",
    "PHA (Polyhydroxy Acid) Serum",
    "Probiotic Serum",
    "Quercetin Serum",
    "Retinol",
    "Rosehip Oil",
    "Serum",
    "Vitamin C Serum",
    "Vitamin E Oil",
    "Sunscreen",
    "Acne Spot Treatment",
    "Pore Minimizer",
    "Spot Treatment",
    "Body Butter",
    "Body Lotion",
    "Body Oil",
    "Body Scrub",
    "Body Moisturizer",
    "Calamine Lotion",
    "Makeup Remover",
    "Micellar Water",
    "Face Balm",
    "Toner",
    "Witch Hazel Toner",
  ];
